SET SQL DIALECT 3;

/* CREATE DATABASE '127.0.0.1/gds_db:C:\Users\Avadh\Desktop\DeleteMe\STUDENTS.ib' USER 'SYSDBA' password 'Enter_Password_here' PAGE_SIZE 4096
 WITH ADMIN OPTION
; */
COMMIT;
/* Users in Database (passwords need to be added)*/
/* CREATE USER SYSDSO SET PASSWORD 'Enter_Password_here' ;*/
/*CONNECT '127.0.0.1/gds_db:C:\Users\Avadh\Desktop\DeleteMe\STUDENTS.ib' USER 'SYSDSO' PASSWORD 'Enter_Password_here'; */
/* ALTER DATABASE SET SYSTEM ENCRYPTION PASSWORD 'Enter_Password_here';*/
CREATE ENCRYPTION DOPES FOR DES WITH LENGTH 56 BITS INIT_VECTOR  NULL PAD  NULL;
/* CREATE ENCRYPTION Neeraj FOR DES WITH LENGTH 56 BITS INIT_VECTOR  NULL PAD  NULL PASSWORD 'Enter_Password_here';*/
GRANT ENCRYPT ON ENCRYPTION DOPES TO SYSDBA;
GRANT ENCRYPT ON ENCRYPTION Neeraj TO SYSDBA;
COMMIT;
/*CONNECT '127.0.0.1/gds_db:C:\Users\Avadh\Desktop\DeleteMe\STUDENTS.ib' USER 'SYSDBA' PASSWORD 'Enter_Password_here'; */
/* Domain definitions */
CREATE DOMAIN D_ADDRESS AS VARCHAR(100) NOT NULL;
CREATE DOMAIN D_BRANCH AS VARCHAR(10) NOT NULL;
CREATE DOMAIN D_COURSE AS VARCHAR(10) NOT NULL;
CREATE DOMAIN D_EMAIL AS VARCHAR(50) CHARACTER SET UTF8 NOT NULL;
CREATE DOMAIN D_FATHER AS VARCHAR(50) NOT NULL;
CREATE DOMAIN D_GENDER AS VARCHAR(10) NOT NULL;
CREATE DOMAIN D_ID AS INTEGER
	 DEFAULT -1 NOT NULL;
CREATE DOMAIN D_MOTHER AS VARCHAR(50) CHARACTER SET UTF8 NOT NULL;
CREATE DOMAIN D_PHONE AS VARCHAR(12) CHARACTER SET UTF8 NOT NULL;
CREATE DOMAIN D_REGISTRATION AS VARCHAR(15) NOT NULL;
CREATE DOMAIN D_STUDENT_NAME AS VARCHAR(50) CHARACTER SET UTF8
	 DEFAULT 'NAME' NOT NULL;
CREATE DOMAIN D_YEAR_ADMISSION AS VARCHAR(4) NOT NULL;

/* Table: STUDENTS, Owner: SYSDBA */
CREATE TABLE STUDENTS
(
        NAME	D_STUDENT_NAME NOT NULL,
        EMAIL	D_EMAIL NOT NULL,
        PHONE	D_PHONE NOT NULL,
        ADDRESS	D_ADDRESS NOT NULL,
        MOTHER	D_MOTHER NOT NULL,
        FATHER	D_FATHER NOT NULL,
        GENDER	D_GENDER NOT NULL,
        BRANCH	D_BRANCH NOT NULL,
        COURSE	D_COURSE NOT NULL,
        REGISTRATION	D_REGISTRATION NOT NULL,
        YEAR_ADMISSION	D_YEAR_ADMISSION NOT NULL
);

/* Subscriptions */
SET AUTODDL OFF;
SET AUTODDL ON;
COMMIT;
COMMIT WORK;

/* Stored procedures */

COMMIT WORK;

/* Grant Roles for this database */


/* Grant permissions for this database */

GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES, DECRYPT ON STUDENTS TO PUBLIC;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES, DECRYPT ON STUDENTS TO SYSDSO WITH GRANT OPTION;

/* Meta data descriptions.  This syntax requires InterBase 2020 or higher.  Some tables require ODS18 and higher */
